---
- name: install docker
  hosts: monitoring
  become: yes

  vars:
    web_message: "Hello from Ansible on {{ inventory_hostname }}"

  tasks:
    - name: install python3
      yum:
        name: python3
        state: present
      when: ansible_distribution == "Amazon"

    - name: Install docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: Restart docker
      service:
        name: docker
        state: restarted