---
- name: Configure web servers
  hosts: web
  become: yes

  vars:
    web_message: "Hello from Ansible on {{ inventory_hostname }}"

  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "Amazon"

    - name: Enable nginx via amazon-linux-extras
      command: amazon-linux-extras enable nginx1
      args:
        creates: /etc/yum.repos.d/amzn2extra-nginx1.repo
      when: ansible_distribution == "Amazon"

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create index.html
      copy:
        content: "{{ web_message }}" #we always use double quotes to ensure safe variable interpolation handeling special characters and spaces and dots correctly
        dest: /usr/share/nginx/html/index.html
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

