- name: Install Nginx on Amazon Linux 2
  hosts: web
  become: yes
  vars:
    web_message: "Hello from Ansible on {{ inventory_hostname }}"
  tasks:
    - name: Enable nginx in amazon-linux-extras
      amazon.aws.aws_ami_extras:
        name: nginx1
        state: enabled

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create index.html
      copy:
        content: "Hello from {{ inventory_hostname }}"
        dest: /usr/share/nginx/html/index.html
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

